In [1]:
import polars as pl

# Q1

## prep

In [5]:
urls = {
    'airports':'https://sacodeassessment.blob.core.windows.net/public/airports.csv'
    , 'countries': 'https://sacodeassessment.blob.core.windows.net/public/countries.csv'
    , 'runways': 'https://sacodeassessment.blob.core.windows.net/public/runways.csv'
}

In [7]:
airports = pl.read_csv(urls['airports'])
countries = pl.read_csv(urls['countries'])
runways = pl.read_csv(urls['runways'],infer_schema_length=10000)

In [9]:
airports.head()

shape: (5, 18)
┌────────┬───────┬─────────────┬─────────────┬───┬────────────┬───────────┬─────────────┬──────────┐
│ id     ┆ ident ┆ type        ┆ name        ┆ … ┆ local_code ┆ home_link ┆ wikipedia_l ┆ keywords │
│ ---    ┆ ---   ┆ ---         ┆ ---         ┆   ┆ ---        ┆ ---       ┆ ink         ┆ ---      │
│ i64    ┆ str   ┆ str         ┆ str         ┆   ┆ str        ┆ str       ┆ ---         ┆ str      │
│        ┆       ┆             ┆             ┆   ┆            ┆           ┆ str         ┆          │
╞════════╪═══════╪═════════════╪═════════════╪═══╪════════════╪═══════════╪═════════════╪══════════╡
│ 6523   ┆ 00A   ┆ heliport    ┆ Total Rf    ┆ … ┆ 00A        ┆ null      ┆ null        ┆ null     │
│        ┆       ┆             ┆ Heliport    ┆   ┆            ┆           ┆             ┆          │
│ 323361 ┆ 00AA  ┆ small_airpo ┆ Aero B      ┆ … ┆ 00AA       ┆ null      ┆ null        ┆ null     │
│        ┆       ┆ rt          ┆ Ranch       ┆   ┆            ┆           ┆             ┆          │
│        ┆       ┆             ┆ Airport     ┆   ┆            ┆           ┆             ┆          │
│ 6524   ┆ 00AK  ┆ small_airpo ┆ Lowell      ┆ … ┆ 00AK       ┆ null      ┆ null        ┆ null     │
│        ┆       ┆ rt          ┆ Field       ┆   ┆            ┆           ┆             ┆          │
│ 6525   ┆ 00AL  ┆ small_airpo ┆ Epps        ┆ … ┆ 00AL       ┆ null      ┆ null        ┆ null     │
│        ┆       ┆ rt          ┆ Airpark     ┆   ┆            ┆           ┆             ┆          │
│ 6526   ┆ 00AR  ┆ closed      ┆ Newport     ┆ … ┆ null       ┆ null      ┆ null        ┆ 00AR     │
│        ┆       ┆             ┆ Hospital &  ┆   ┆            ┆           ┆             ┆          │
│        ┆       ┆             ┆ Clinic      ┆   ┆            ┆           ┆             ┆          │
│        ┆       ┆             ┆ Helipo…     ┆   ┆            ┆           ┆             ┆          │
└────────┴───────┴─────────────┴─────────────┴───┴────────────┴───────────┴─────────────┴──────────┘

In [11]:
countries.head()

shape: (5, 6)
┌────────┬──────┬──────────────────────┬───────────┬───────────────────────┬───────────────────────┐
│ id     ┆ code ┆ name                 ┆ continent ┆ wikipedia_link        ┆ keywords              │
│ ---    ┆ ---  ┆ ---                  ┆ ---       ┆ ---                   ┆ ---                   │
│ i64    ┆ str  ┆ str                  ┆ str       ┆ str                   ┆ str                   │
╞════════╪══════╪══════════════════════╪═══════════╪═══════════════════════╪═══════════════════════╡
│ 302672 ┆ AD   ┆ Andorra              ┆ EU        ┆ https://en.wikipedia. ┆ null                  │
│        ┆      ┆                      ┆           ┆ org/wiki/An…          ┆                       │
│ 302618 ┆ AE   ┆ United Arab Emirates ┆ AS        ┆ https://en.wikipedia. ┆ UAE,مطارات في         │
│        ┆      ┆                      ┆           ┆ org/wiki/Un…          ┆ الإمارات العربية ا…   │
│ 302619 ┆ AF   ┆ Afghanistan          ┆ AS        ┆ https://en.wikipedia. ┆ null                  │
│        ┆      ┆                      ┆           ┆ org/wiki/Af…          ┆                       │
│ 302722 ┆ AG   ┆ Antigua and Barbuda  ┆ NA        ┆ https://en.wikipedia. ┆ null                  │
│        ┆      ┆                      ┆           ┆ org/wiki/An…          ┆                       │
│ 302723 ┆ AI   ┆ Anguilla             ┆ NA        ┆ https://en.wikipedia. ┆ null                  │
│        ┆      ┆                      ┆           ┆ org/wiki/An…          ┆                       │
└────────┴──────┴──────────────────────┴───────────┴───────────────────────┴───────────────────────┘

In [13]:
runways.head()

shape: (5, 20)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id     ┆ airport_re ┆ airport_id ┆ length_ft ┆ … ┆ he_longit ┆ he_elevat ┆ he_headin ┆ he_displa │
│ ---    ┆ f          ┆ ent        ┆ ---       ┆   ┆ ude_deg   ┆ ion_ft    ┆ g_degT    ┆ ced_thres │
│ i64    ┆ ---        ┆ ---        ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ hold_ft   │
│        ┆ i64        ┆ str        ┆           ┆   ┆ f64       ┆ i64       ┆ f64       ┆ ---       │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ i64       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 269408 ┆ 6523       ┆ 00A        ┆ 80        ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 255155 ┆ 6524       ┆ 00AK       ┆ 2500      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 254165 ┆ 6525       ┆ 00AL       ┆ 2300      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 270932 ┆ 6526       ┆ 00AR       ┆ 40        ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 322128 ┆ 322127     ┆ 00AS       ┆ 1450      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [16]:
airports.describe()

shape: (9, 19)
┌────────────┬────────────┬───────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ id         ┆ ident ┆ type       ┆ … ┆ local_cod ┆ home_link ┆ wikipedia ┆ keywords  │
│ ---        ┆ ---        ┆ ---   ┆ ---        ┆   ┆ e         ┆ ---       ┆ _link     ┆ ---       │
│ str        ┆ f64        ┆ str   ┆ str        ┆   ┆ ---       ┆ str       ┆ ---       ┆ str       │
│            ┆            ┆       ┆            ┆   ┆ str       ┆           ┆ str       ┆           │
╞════════════╪════════════╪═══════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 63253.0    ┆ 63253 ┆ 63253      ┆ … ┆ 31246     ┆ 3242      ┆ 10274     ┆ 11489     │
│ null_count ┆ 0.0        ┆ 0     ┆ 0          ┆ … ┆ 32007     ┆ 60011     ┆ 52979     ┆ 51764     │
│ mean       ┆ 116589.540 ┆ null  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆ 828        ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ std        ┆ 141141.632 ┆ null  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│            ┆ 232        ┆       ┆            ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 2.0        ┆ 00A   ┆ balloonpor ┆ … ┆ -         ┆ http://81 ┆ http://de ┆ "El       │
│            ┆            ┆       ┆ t          ┆   ┆           ┆ 3.mnd.gov ┆ .wikipedi ┆ Ciprés"   │
│            ┆            ┆       ┆            ┆   ┆           ┆ .tw/engli ┆ a.org/wik ┆ Military  │
│            ┆            ┆       ┆            ┆   ┆           ┆ sh/       ┆ i/Alb…    ┆ Airbase   │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆           ┆ Num…      │
│ 25%        ┆ 15946.0    ┆ null  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ 32036.0    ┆ null  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ 317302.0   ┆ null  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max        ┆ 342279.0   ┆ spgl  ┆ small_airp ┆ … ┆ ZZV       ┆ https://y ┆ https://z ┆ 황수원비  │
│            ┆            ┆       ┆ ort        ┆   ┆           ┆ yb.ca/    ┆ h.wikiped ┆ 행장, 黃  │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ ia.org/wi ┆ 水院飛行  │
│            ┆            ┆       ┆            ┆   ┆           ┆           ┆ ki/%E…    ┆ 場        │
└────────────┴────────────┴───────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [18]:
airports.select(
    pl.all().n_unique()
)

shape: (1, 18)
┌───────┬───────┬──────┬───────┬───┬────────────┬───────────┬────────────────┬──────────┐
│ id    ┆ ident ┆ type ┆ name  ┆ … ┆ local_code ┆ home_link ┆ wikipedia_link ┆ keywords │
│ ---   ┆ ---   ┆ ---  ┆ ---   ┆   ┆ ---        ┆ ---       ┆ ---            ┆ ---      │
│ u32   ┆ u32   ┆ u32  ┆ u32   ┆   ┆ u32        ┆ u32       ┆ u32            ┆ u32      │
╞═══════╪═══════╪══════╪═══════╪═══╪════════════╪═══════════╪════════════════╪══════════╡
│ 63253 ┆ 63253 ┆ 7    ┆ 60023 ┆ … ┆ 29700      ┆ 3228      ┆ 10202          ┆ 11207    │
└───────┴───────┴──────┴───────┴───┴────────────┴───────────┴────────────────┴──────────┘

In [20]:
countries.describe()

shape: (9, 7)
┌────────────┬──────────┬──────┬─────────────┬───────────┬────────────────────┬────────────────────┐
│ statistic  ┆ id       ┆ code ┆ name        ┆ continent ┆ wikipedia_link     ┆ keywords           │
│ ---        ┆ ---      ┆ ---  ┆ ---         ┆ ---       ┆ ---                ┆ ---                │
│ str        ┆ f64      ┆ str  ┆ str         ┆ str       ┆ str                ┆ str                │
╞════════════╪══════════╪══════╪═════════════╪═══════════╪════════════════════╪════════════════════╡
│ count      ┆ 247.0    ┆ 247  ┆ 247         ┆ 247       ┆ 247                ┆ 93                 │
│ null_count ┆ 0.0      ┆ 0    ┆ 0           ┆ 0         ┆ 0                  ┆ 154                │
│ mean       ┆ 302679.0 ┆ null ┆ null        ┆ null      ┆ null               ┆ null               │
│ std        ┆ 71.44695 ┆ null ┆ null        ┆ null      ┆ null               ┆ null               │
│ min        ┆ 302556.0 ┆ AD   ┆ Afghanistan ┆ AF        ┆ https://en.wikiped ┆ Aeroporti d'Italia │
│            ┆          ┆      ┆             ┆           ┆ ia.org/wiki/Af…    ┆                    │
│ 25%        ┆ 302618.0 ┆ null ┆ null        ┆ null      ┆ null               ┆ null               │
│ 50%        ┆ 302679.0 ┆ null ┆ null        ┆ null      ┆ null               ┆ null               │
│ 75%        ┆ 302741.0 ┆ null ┆ null        ┆ null      ┆ null               ┆ null               │
│ max        ┆ 302802.0 ┆ ZZ   ┆ Zimbabwe    ┆ SA        ┆ https://en.wikiped ┆ 한국의 공항        │
│            ┆          ┆      ┆             ┆           ┆ ia.org/wiki/Zi…    ┆                    │
└────────────┴──────────┴──────┴─────────────┴───────────┴────────────────────┴────────────────────┘

In [22]:
runways.describe()

shape: (9, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ id        ┆ airport_r ┆ airport_i ┆ … ┆ he_longit ┆ he_elevat ┆ he_headin ┆ he_displ │
│ ---       ┆ ---       ┆ ef        ┆ dent      ┆   ┆ ude_deg   ┆ ion_ft    ┆ g_degT    ┆ aced_thr │
│ str       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ eshold_f │
│           ┆           ┆ f64       ┆ str       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ t        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 41811.0   ┆ 41811.0   ┆ 41811     ┆ … ┆ 14526.0   ┆ 12203.0   ┆ 16087.0   ┆ 3138.0   │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0         ┆ … ┆ 27285.0   ┆ 29608.0   ┆ 25724.0   ┆ 38673.0  │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 257669.41 ┆ 34968.662 ┆ null      ┆ … ┆ -40.06072 ┆ 1055.0394 ┆ 261.78785 ┆ 535.7313 │
│           ┆ 5608      ┆ 983       ┆           ┆   ┆           ┆ 17        ┆ 5         ┆ 58       │
│ std       ┆ 21970.279 ┆ 69876.061 ┆ null      ┆ … ┆ 79.824659 ┆ 1458.3885 ┆ 78.417155 ┆ 465.7251 │
│           ┆ 462       ┆ 079       ┆           ┆   ┆           ┆ 42        ┆           ┆ 47       │
│ min       ┆ 232758.0  ┆ 2.0       ┆ 00A       ┆ … ┆ -178.292  ┆ -1210.0   ┆ 0.0       ┆ 1.0      │
│ 25%       ┆ 243224.0  ┆ 8580.0    ┆ null      ┆ … ┆ -96.603   ┆ 116.0     ┆ 226.0     ┆ 228.0    │
│ 50%       ┆ 253682.0  ┆ 18751.0   ┆ null      ┆ … ┆ -80.2319  ┆ 564.0     ┆ 270.0     ┆ 400.0    │
│ 75%       ┆ 264151.0  ┆ 27543.0   ┆ null      ┆ … ┆ 15.5385   ┆ 1240.0    ┆ 316.0     ┆ 696.0    │
│ max       ┆ 342131.0  ┆ 342052.0  ┆ rjns      ┆ … ┆ 179.343   ┆ 13314.0   ┆ 363.0     ┆ 5001.0   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
countries.select(
    pl.all().n_unique()
)

shape: (1, 6)
┌─────┬──────┬──────┬───────────┬────────────────┬──────────┐
│ id  ┆ code ┆ name ┆ continent ┆ wikipedia_link ┆ keywords │
│ --- ┆ ---  ┆ ---  ┆ ---       ┆ ---            ┆ ---      │
│ u32 ┆ u32  ┆ u32  ┆ u32       ┆ u32            ┆ u32      │
╞═════╪══════╪══════╪═══════════╪════════════════╪══════════╡
│ 247 ┆ 247  ┆ 247  ┆ 7         ┆ 247            ┆ 94       │
└─────┴──────┴──────┴───────────┴────────────────┴──────────┘

## Q1.1

In [27]:
countries_by_airports = countries.select(['code','name']).join(
    airports.group_by('iso_country').agg(
        pl.col('id').count().alias('airport_count')
    )    
    , how= 'left'
    , left_on =  'code'
    , right_on = 'iso_country'
).filter(~ ((pl.col('code') == 'ZZ') & pl.col('airport_count').is_null()) )\
.with_columns(
    pl.col("airport_count").fill_null(0)
)

In [29]:
top_filter = pl.col("airport_count").rank(method="min",descending=True) <=3
countries_by_airports.filter(top_filter).sort('airport_count', descending = True)

shape: (3, 3)
┌──────┬───────────────┬───────────────┐
│ code ┆ name          ┆ airport_count │
│ ---  ┆ ---           ┆ ---           │
│ str  ┆ str           ┆ u32           │
╞══════╪═══════════════╪═══════════════╡
│ US   ┆ United States ┆ 25170         │
│ BR   ┆ Brazil        ┆ 5546          │
│ CA   ┆ Canada        ┆ 2829          │
└──────┴───────────────┴───────────────┘

In [31]:
pl.Config.set_tbl_rows(-1)
bottom_filter =  pl.col("airport_count").rank(method="min",descending=False) <= 10
countries_by_airports.filter(bottom_filter).sort('airport_count', descending = True)

shape: (17, 3)
┌──────┬───────────────────────────────────┬───────────────┐
│ code ┆ name                              ┆ airport_count │
│ ---  ┆ ---                               ┆ ---           │
│ str  ┆ str                               ┆ u32           │
╞══════╪═══════════════════════════════════╪═══════════════╡
│ BL   ┆ Saint Barthélemy                  ┆ 1             │
│ CC   ┆ Cocos (Keeling) Islands           ┆ 1             │
│ CW   ┆ Curaçao                           ┆ 1             │
│ CX   ┆ Christmas Island                  ┆ 1             │
│ GI   ┆ Gibraltar                         ┆ 1             │
│ GM   ┆ Gambia                            ┆ 1             │
│ IO   ┆ British Indian Ocean Territory    ┆ 1             │
│ JE   ┆ Jersey                            ┆ 1             │
│ NF   ┆ Norfolk Island                    ┆ 1             │
│ NR   ┆ Nauru                             ┆ 1             │
│ NU   ┆ Niue                              ┆ 1             │
│ SX   ┆ Sint Maarten                      ┆ 1             │
│ VA   ┆ Vatican City                      ┆ 1             │
│ YT   ┆ Mayotte                           ┆ 1             │
│ GS   ┆ South Georgia and the South Sand… ┆ 0             │
│ PN   ┆ Pitcairn                          ┆ 0             │
│ TK   ┆ Tokelau                           ┆ 0             │
└──────┴───────────────────────────────────┴───────────────┘

## Q1.2

In [34]:
longest_runways_per_airport = runways.select(['airport_ref', 'length_ft', 'width_ft']).filter(
    pl.col("length_ft")
    .rank(method="min", descending=True)
    .over("airport_ref") == 1
)

In [36]:
longest_runways_per_country=airports.select(['id','name','iso_country'])\
.join(
    longest_runways_per_airport
    , how = 'inner'
    , left_on = 'id'
    , right_on = 'airport_ref'
).filter(
    pl.col("length_ft")
    .rank(method="min", descending=True)
    .over("iso_country") == 1
).sort('length_ft', descending = True)

In [38]:
longest_runways_per_country.head()

shape: (5, 5)
┌───────┬─────────────────────────────────┬─────────────┬───────────┬──────────┐
│ id    ┆ name                            ┆ iso_country ┆ length_ft ┆ width_ft │
│ ---   ┆ ---                             ┆ ---         ┆ ---       ┆ ---      │
│ i64   ┆ str                             ┆ str         ┆ i64       ┆ i64      │
╞═══════╪═════════════════════════════════╪═════════════╪═══════════╪══════════╡
│ 46491 ┆ Pontiac Airpark Water Aerodrome ┆ CA          ┆ 120000    ┆ 1000     │
│ 22159 ┆ Gunflint Seaplane Base          ┆ US          ┆ 30000     ┆ 5000     │
│ 30788 ┆ Qamdo Bangda Airport            ┆ CN          ┆ 18045     ┆ 148      │
│ 26407 ┆ Ulyanovsk East Airport          ┆ RU          ┆ 16404     ┆ 323      │
│ 2847  ┆ Pierre Van Ryneveld Airport     ┆ ZA          ┆ 16076     ┆ 197      │
└───────┴─────────────────────────────────┴─────────────┴───────────┴──────────┘

In [40]:
longest_runways_per_country.write_csv('longest_runways_per_country.csv')

# Q2

In [25]:

date = '20260301'
initials = 'ms'
upload_info ={
    'account_name': 'sacodeassessment'
    , 'share_signature': 'sv=2022-11-02&ss=b&srt=o&sp=wc&se=2034-11-11T11:00:00Z&st=2024-11-10T23:00:00Z&spr=https&sig=D%2BgRbWPJDTmsbPtyfTEiTnb7gg594uNsvm62oQK49Yg%3D'
    , 'blob_container' : 'results'
    , 'blob_path' : f'''/ingest-assessment-{date}-{initials}'''
    , 'file':'longest_runways_per_country.csv'
}

In [26]:
azure_url = (
    f'''https://{upload_info['account_name']}.blob.core.windows.net'''
    f'''/{upload_info['blob_container']}/{upload_info['blob_path']}'''
    f'''/{upload_info['file']}'''
    f'''?{upload_info['share_signature']}'''
)
azure_url

'https://sacodeassessment.blob.core.windows.net/results//ingest-assessment-20260301-ms/longest_runways_per_country.csv?sv=2022-11-02&ss=b&srt=o&sp=wc&se=2034-11-11T11:00:00Z&st=2024-11-10T23:00:00Z&spr=https&sig=D%2BgRbWPJDTmsbPtyfTEiTnb7gg594uNsvm62oQK49Yg%3D'

In [27]:
!curl -X PUT "{azure_url}" --data-binary @"{upload_info['file']}" -H "x-ms-blob-type: BlockBlob" -v

* Host sacodeassessment.blob.core.windows.net:443 was resolved.
* IPv6: (none)
* IPv4: 20.209.73.130
*   Trying 20.209.73.130:443...
* Connected to sacodeassessment.blob.core.windows.net (20.209.73.130) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /opt/anaconda3/ssl/cacert.pem
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / secp384r1 / RSASSA-PSS
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: C=US; ST=WA; L=Redmond; O=Microsoft Corporation; CN=*.blob.core.windows.net
*  start date: Jan 23 14:07:34 2026 GMT
*  expire date: Jul 22 14:07:34 2026 GMT
*  subjectAltName: host "sacodeassessment.blob.core.windows.net" matched cert's "*.blob.core.windows.net"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft Azure RSA TLS Issuing CA 04
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha384WithRSAEncryption
*   Certificate level 1: Public key type RSA (4096/152 Bits/secBits), signed using sha384WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
> PUT /results//ingest-assessment-20260301-ms/longest_runways_per_country.csv?sv=2022-11-02&ss=b&srt=o&sp=wc&se=2034-11-11T11:00:00Z&st=2024-11-10T23:00:00Z&spr=https&sig=D%2BgRbWPJDTmsbPtyfTEiTnb7gg594uNsvm62oQK49Yg%3D HTTP/1.1
> Host: sacodeassessment.blob.core.windows.net
> User-Agent: curl/8.5.0
> Accept: */*
> x-ms-blob-type: BlockBlob
> Content-Length: 13067
> Content-Type: application/x-www-form-urlencoded
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/1.1 201 Created
< Content-Length: 0
< Content-MD5: /QvoFLGE4IKe6F9pXyJbMQ==
< Last-Modified: Sun, 01 Mar 2026 22:27:07 GMT
< ETag: "0x8DE77E1AC4D0FE7"
< Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
< x-ms-request-id: fd95bdb7-d01e-006e-78ca-a97d66000000
< x-ms-version: 2022-11-02
< x-ms-content-crc64: TOteMkhkaR4=
< x-ms-request-server-encrypted: true
< Date: Sun, 01 Mar 2026 22:27:06 GMT
<
* Connection #0 to host sacodeassessment.blob.core.windows.net left intact

In [28]:
# read_url = azure_url.replace('&sp=wc','&sp=rw')
# read_url

In [43]:
# !curl "{read_url}" | head -3

# Q3

In [52]:
import requests
import json
from pathlib import Path
import time

In [54]:
iso_countries = sorted(airports['iso_country'].unique().to_list())
iso_countries[:5]

['AD', 'AE', 'AF', 'AG', 'AI']

In [56]:

client_id=  'abc123'
host = 'code001.ecsbdp.com'
upload_path = f'{host}/revenues?client={client_id}'

In [60]:
for iso in ['us']:
    print(f'https://{host}/countries/{iso}?client={client_id}')

https://code001.ecsbdp.com/countries/us?client=abc123

In [74]:
data = []
missing = []

for iso in iso_countries:
    url = f'https://{host}/countries/{iso.lower()}.csv'
    try:
        resp = requests.get(url, timeout=(1, 5))
        if resp.status_code == 200:
            data.append({'iso': iso, 'data': resp.json()})
            print(f'added {iso} data')
        else:
            missing.append(iso)
            print(f'''couldn't find {iso} data''')
    except Exception as e:
        missing.append(iso)
        print(f'{iso}: Unexpected {type(e).__name__}: {e}')
    time.sleep(0.2)

AD: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ad.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e798a50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AE: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ae.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e747990>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AF: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/af.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e65ae50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AG: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ag.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7cb2d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AI: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ai.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e744f10>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AL: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/al.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e798f50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AM: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/am.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7c8a90>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AO: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ao.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e6336d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AQ: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/aq.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e788990>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AR: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ar.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e78b250>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AS: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/as.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e788fd0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AT: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/at.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e78b910>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AU: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/au.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e78b490>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AW: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/aw.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e79b0d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
AZ: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/az.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7cbd90>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BA: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ba.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7476d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BB: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bb.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7751d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BD: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bd.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e65ae50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BE: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/be.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7cb650>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BF: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bf.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7cbf50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BG: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bg.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e79b3d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BH: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bh.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e5c5dd0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BI: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bi.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e78b950>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BJ: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bj.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e78bcd0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BL: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bl.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e5b5650>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BM: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bm.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7983d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BN: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bn.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e78b310>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BO: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bo.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e6497d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BQ: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bq.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7c8210>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BR: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/br.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e746f10>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BS: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bs.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e775150>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BT: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bt.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e747a50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BW: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bw.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7c8b50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BY: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/by.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e79b310>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
BZ: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/bz.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e789950>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CA: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ca.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e78b350>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CC: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cc.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7771d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CD: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cd.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e778950>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CF: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cf.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e79aad0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CG: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cg.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7c9990>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CH: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ch.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e744a50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CI: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ci.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e78a890>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CK: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ck.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16cdf5510>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CL: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cl.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16dc071d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CM: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cm.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16dc1ba50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CN: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cn.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e64a110>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CO: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/co.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7ca710>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CR: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cr.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e79a710>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CU: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cu.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7880d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CV: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cv.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7748d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CW: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cw.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e5e21d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CX: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cx.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e798350>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CY: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cy.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e79a550>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
CZ: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/cz.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7cab50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
DE: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/de.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e789b90>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
DJ: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/dj.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e78ba90>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
DK: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/dk.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e777090>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
DM: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/dm.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e671210>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
DO: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/do.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e64bd50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
DZ: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/dz.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e7cb450>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
EC: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ec.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e774890>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
EE: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/ee.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e78b710>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
EG: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/eg.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e79bf90>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
EH: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/eh.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e6707d0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
ER: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/er.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e5e3b50>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
ES: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/es.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e799fd0>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))
ET: Unexpected ConnectTimeout: HTTPSConnectionPool(host='code001.ecsbdp.com', port=443): Max retries exceeded with url: /countries/et.csv (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x16e789b90>, 'Connection to code001.ecsbdp.com timed out. (connect timeout=1)'))

KeyboardInterrupt:

In [ ]:
with Path('countries_data.json').open('w') as f:
    json.dump(data, f)

In [86]:
revenues_url = f'https://{host}/revenues?client={client_id}'
with open('revenues.txt', 'w') as f: pass
requests.post(revenues_url, files={'file': open('revenues.txt', 'rb')})

KeyboardInterrupt:

# Q4

In [41]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.11/site-packages (2.9.11)

[notice] A new release of pip is available: 24.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [200]:
import psycopg2
conn = psycopg2.connect(host="code001.ecsbdp.com", port=5432, dbname="chinook", user="larry", password="iddqd")

In [82]:
tables = pl.read_database("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;", conn)
tables

shape: (11, 1)
┌────────────────┐
│ table_name     │
│ ---            │
│ str            │
╞════════════════╡
│ album          │
│ artist         │
│ customer       │
│ employee       │
│ genre          │
│ invoice        │
│ invoice_line   │
│ media_type     │
│ playlist       │
│ playlist_track │
│ track          │
└────────────────┘

In [84]:
desc = pl.read_database("""
  SELECT table_name, column_name, data_type, is_nullable
  FROM information_schema.columns 
  WHERE table_schema = 'public' 
  ORDER BY table_name, ordinal_position
""", conn)
desc.head()

shape: (5, 4)
┌────────────┬─────────────┬───────────────────┬─────────────┐
│ table_name ┆ column_name ┆ data_type         ┆ is_nullable │
│ ---        ┆ ---         ┆ ---               ┆ ---         │
│ str        ┆ str         ┆ str               ┆ str         │
╞════════════╪═════════════╪═══════════════════╪═════════════╡
│ album      ┆ album_id    ┆ integer           ┆ NO          │
│ album      ┆ title       ┆ character varying ┆ NO          │
│ album      ┆ artist_id   ┆ integer           ┆ NO          │
│ artist     ┆ artist_id   ┆ integer           ┆ NO          │
│ artist     ┆ name        ┆ character varying ┆ YES         │
└────────────┴─────────────┴───────────────────┴─────────────┘

64

track name
shape: (1, 1)
┌───────────────────────────────────┐
│ name                              │
│ ---                               │
│ str                               │
╞═══════════════════════════════════╡
│ The Four Horsemen FLAG{e9613d97-… │
└───────────────────────────────────┘

In [45]:
# │ invoice        ┆ customer_id         ┆ integer                     ┆ NO          │
# │ invoice        ┆ total               ┆ numeric                     ┆ NO          │
# │ invoice_line   ┆ track_id            ┆ integer                     ┆ NO          │
# │ track          ┆ track_id            ┆ integer                     ┆ NO          │
# │ track          ┆ genre_id            ┆ integer                     ┆ YES         │
# | genre          ┆ genre_id            ┆ integer                     ┆ NO          │
# │ genre          ┆ name                ┆ character varying           ┆ YES

In [47]:
import psycopg2
conn = psycopg2.connect(host="code001.ecsbdp.com", port=5432, dbname="chinook", user="larry", password="iddqd")
pl.read_database(
    """
    WITH track_type AS (
        SELECT
            track_id
            , CASE WHEN g.name = 'Jazz' THEN 1 ELSE 0 END AS is_jazz
        FROM track AS t
        LEFT JOIN genre AS g USING (genre_id)
    )
    , customer_sales_by_type AS (
        SELECT
            customer_id
            , MAX(is_jazz) AS is_jazz_customer
            , SUM(total) total_sales
        FROM invoice AS i
        LEFT JOIN invoice_line AS il USING(invoice_id)
        LEFT JOIN track_type AS tt USING(track_id)
        GROUP BY customer_id
    )
    SELECT 
        is_jazz_customer
        , SUM(total_sales) AS total_sales
    FROM customer_sales_by_type
    GROUP BY is_jazz_customer
    """
    , conn
)

shape: (2, 2)
┌──────────────────┬──────────────┐
│ is_jazz_customer ┆ total_sales  │
│ ---              ┆ ---          │
│ i64              ┆ decimal[*,2] │
╞══════════════════╪══════════════╡
│ 0                ┆ 9762.74      │
│ 1                ┆ 11085.88     │
└──────────────────┴──────────────┘

In [53]:
pl.read_database(
    """
    SELECT album.title
    FROM track
    JOIN album ON (track.album_id = album.album_id)
    WHERE LOWER(track.name) = LOWER('Enter Sandman')
    """
    , conn
)

shape: (2, 1)
┌────────────────────────────────┐
│ title                          │
│ ---                            │
│ str                            │
╞════════════════════════════════╡
│ Plays Metallica By Four Cellos │
│ Black Album                    │
└────────────────────────────────┘

In [55]:
""""
Solution 2: Indexing (normal)
CREATE INDEX idx_track_name_lower ON track (LOWER(name));
Solution 2: Trigram
CREATE INDEX idx_track_name_trgm ON track USING GIN (name gin_trgm_ops);
"""

'"\nSolution 2: Indexing (normal)\nCREATE INDEX idx_track_name_lower ON track (LOWER(name));\nSolution 2: Trigram\nCREATE INDEX idx_track_name_trgm ON track USING GIN (name gin_trgm_ops);\n'

# Q5

In [80]:
import base64
import json
import jwt
from datetime import datetime

token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZ\
yIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL0VuZWNvLm\
9ubWljcm9zb2Z0LmNvbS9lY3Nhei1hcGlnZWUtb2RwLXQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dz\
Lm5ldC9lY2EzNjA1NC00OWE5LTQ3MzEtYTQyZi04NDAwNjcwZmMwMjIvIiwiaWF0IjoxNjE2NDE2NzA1LC\
JuYmYiOjE2MTY0MTY3MDUsImV4cCI6MTYxNjQyMDYwNSwiYWlvIjoiRTJaZ1lFZzNWZG1mNmhzcHYvdVBN\
YmZmOC9NQ0FBPT0iLCJhcHBpZCI6IjFlMGZiMzU0LWE3OGQtNGY1Yi05OTY2LWVkNjIzYTYyNDU5OSIsI\
mlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2VjYTM2MDU0LTQ5YTktNDczMS1hNDJmLTg0MDA2NzB\
mYzAyMi8iLCJvaWQiOiJkYjZlODlmOS1kYjE2LTQyNTItOTQyOS1jNGQ1ZTQ4YWRhYmQiLCJzdWIiOiJk\
YjZlODlmOS1kYjE2LTQyNTItOTQyOS1jNGQ1ZTQ4YWRhYmQiLCJ0aWQiOiJlY2EzNjA1NC00OWE5LTQ3M\
zEtYTQyZi04NDAwNjcwZmMwMjIiLCJ1dGkiOiJTZ0JhN1EzS1RVeTNRZjhoek9ZM0FBIiwidmVyIjoiMS\
4wIn0.AZRHBIxtI9uOT99Q0WRII1wPLKbrcBU-BHmQfUvaCCAnKApOZyrH3kxxtYjejgDTnoPIS0I1NnH0p\
xNd2ATN50fcHjsXkCr3DaspJggLSp2rT2nBMkTDyPBKIzw6rZ9tRrwsuFVXh2cYP1kIgoX-PxpWfzIsyXc\
tcSzbgYnLOJpiVDiZuzhi4YWbmvclO5iezLLpXvQ0ER034tco9An6LtAGH0mK0-4FHW4McQGLpWPXhwAVL\
RzNdCXx4TNnOK7eDAVyvxffDlbG9OSmd-PnLbFJKHwWNan06D7hTC8yQa4k-k0gcnHjDYKirG7CfnR5b6d\
KSst-BCa3X9w"

header, payload, signature = token.split('.')

header_json = base64.urlsafe_b64decode(header + '==').decode()
payload_json = base64.urlsafe_b64decode(payload + '==').decode()

header_decoded = json.loads(header_json)
payload_decoded = json.loads(payload_json)

print("=== HEADER ===")
print(header_decoded)
print("\n=== PAYLOAD ===")
print(payload_decoded)

exp_unix = payload_decoded['exp']
exp_date = datetime.fromtimestamp(exp_unix).strftime('%Y-%m-%d %H:%M UTC')
print(f"Expiry: {exp_date}")

print(f"Issuer: {payload_decoded['iss']}")
print(f"Audience: {payload_decoded['aud']}")
print(f"App ID: {payload_decoded['appid']}")
# print(f"Roles: {payload_decoded['roles']}")

decoded = jwt.decode(token, options={"verify_signature": False})
print("\n=== FULL DECODE ===")
print(decoded)

=== HEADER ===
{'typ': 'JWT', 'alg': 'RS256', 'x5t': 'nOo3ZDrODXEK1jKWhXslHR_KXEg', 'kid': 'nOo3ZDrODXEK1jKWhXslHR_KXEg'}

=== PAYLOAD ===
{'aud': 'https://Eneco.onmicrosoft.com/ecsaz-apigee-odp-t', 'iss': 'https://sts.windows.net/eca36054-49a9-4731-a42f-8400670fc022/', 'iat': 1616416705, 'nbf': 1616416705, 'exp': 1616420605, 'aio': 'E2ZgYEg3Vdmf6hspv/uPMbff8/MCAA==', 'appid': '1e0fb354-a78d-4f5b-9966-ed623a624599', 'idp': 'https://sts.windows.net/eca36054-49a9-4731-a42f-8400670fc022/', 'oid': 'db6e89f9-db16-4252-9429-c4d5e48adabd', 'sub': 'db6e89f9-db16-4252-9429-c4d5e48adabd', 'tid': 'eca36054-49a9-4731-a42f-8400670fc022', 'uti': 'SgBa7Q3KTUy3Qf8hzOY3AA', 'ver': '1.0'}
Expiry: 2021-03-22 14:43 UTC
Issuer: https://sts.windows.net/eca36054-49a9-4731-a42f-8400670fc022/
Audience: https://Eneco.onmicrosoft.com/ecsaz-apigee-odp-t
App ID: 1e0fb354-a78d-4f5b-9966-ed623a624599

=== FULL DECODE ===
{'aud': 'https://Eneco.onmicrosoft.com/ecsaz-apigee-odp-t', 'iss': 'https://sts.windows.net/eca36054-49a9-4731-a42f-8400670fc022/', 'iat': 1616416705, 'nbf': 1616416705, 'exp': 1616420605, 'aio': 'E2ZgYEg3Vdmf6hspv/uPMbff8/MCAA==', 'appid': '1e0fb354-a78d-4f5b-9966-ed623a624599', 'idp': 'https://sts.windows.net/eca36054-49a9-4731-a42f-8400670fc022/', 'oid': 'db6e89f9-db16-4252-9429-c4d5e48adabd', 'sub': 'db6e89f9-db16-4252-9429-c4d5e48adabd', 'tid': 'eca36054-49a9-4731-a42f-8400670fc022', 'uti': 'SgBa7Q3KTUy3Qf8hzOY3AA', 'ver': '1.0'}

# Q6

In [58]:
!echo "RkxBR3s3Mjc0ZTVkYy1hYjYwLTRmYzItOGY1MS1lZTZlY2ViNmJlZjd9" | base64 -d

FLAG{7274e5dc-ab60-4fc2-8f51-ee6eceb6bef7}

In [60]:
list(urls.values())

['https://sacodeassessment.blob.core.windows.net/public/airports.csv',
 'https://sacodeassessment.blob.core.windows.net/public/countries.csv',
 'https://sacodeassessment.blob.core.windows.net/public/runways.csv']

In [166]:
countries.filter(
    pl.max_horizontal(pl.selectors.string().str.contains('FLAG|rxkob'))
)

shape: (1, 6)
┌────────┬──────┬────────┬───────────┬──────────────────────────────┬──────────────────────────────┐
│ id     ┆ code ┆ name   ┆ continent ┆ wikipedia_link               ┆ keywords                     │
│ ---    ┆ ---  ┆ ---    ┆ ---       ┆ ---                          ┆ ---                          │
│ i64    ┆ str  ┆ str    ┆ str       ┆ str                          ┆ str                          │
╞════════╪══════╪════════╪═══════════╪══════════════════════════════╪══════════════════════════════╡
│ 302629 ┆ CY   ┆ Cyprus ┆ AS        ┆ https://en.wikipedia.org/wik ┆ FLAG{e9cade1a-55a8-4af5-887d │
│        ┆      ┆        ┆           ┆ i/Cy…                        ┆ -a70…                        │
└────────┴──────┴────────┴───────────┴──────────────────────────────┴──────────────────────────────┘

In [168]:
airports.filter(
    pl.max_horizontal(pl.selectors.string().str.contains('FLAG|rxkob'))
)

shape: (0, 18)
┌─────┬───────┬──────┬──────┬───┬────────────┬───────────┬────────────────┬──────────┐
│ id  ┆ ident ┆ type ┆ name ┆ … ┆ local_code ┆ home_link ┆ wikipedia_link ┆ keywords │
│ --- ┆ ---   ┆ ---  ┆ ---  ┆   ┆ ---        ┆ ---       ┆ ---            ┆ ---      │
│ i64 ┆ str   ┆ str  ┆ str  ┆   ┆ str        ┆ str       ┆ str            ┆ str      │
╞═════╪═══════╪══════╪══════╪═══╪════════════╪═══════════╪════════════════╪══════════╡
└─────┴───────┴──────┴──────┴───┴────────────┴───────────┴────────────────┴──────────┘

In [170]:
runways.filter(
    pl.max_horizontal(pl.selectors.string().str.contains('FLAG|rxkob'))
)

shape: (0, 20)
┌─────┬────────────┬────────────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ id  ┆ airport_re ┆ airport_id ┆ length_ft ┆ … ┆ he_longitu ┆ he_elevati ┆ he_heading ┆ he_displa │
│ --- ┆ f          ┆ ent        ┆ ---       ┆   ┆ de_deg     ┆ on_ft      ┆ _degT      ┆ ced_thres │
│ i64 ┆ ---        ┆ ---        ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ hold_ft   │
│     ┆ i64        ┆ str        ┆           ┆   ┆ f64        ┆ i64        ┆ f64        ┆ ---       │
│     ┆            ┆            ┆           ┆   ┆            ┆            ┆            ┆ i64       │
╞═════╪════════════╪════════════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
└─────┴────────────┴────────────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [63]:
urls_str = ' '.join(urls.values())
urls_str

'https://sacodeassessment.blob.core.windows.net/public/airports.csv https://sacodeassessment.blob.core.windows.net/public/countries.csv https://sacodeassessment.blob.core.windows.net/public/runways.csv'

In [65]:
%%bash -s "$urls_str"
read -a urls <<< "$1"
for url in "${urls[@]}"; do
  fn=$(basename "$url")
  curl -O "$url" && echo "✅ $fn"
  echo "=== $fn flags ==="
  grep -i 'FLAG{' "$fn"
  grep 'RkxBR3s' "$fn"
  echo "---"
done

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9127k  100 9127k    0     0  8226k      0  0:00:01  0:00:01 --:--:-- 8229k

✅ airports.csv
=== airports.csv flags ===
---

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20707  100 20707    0     0   240k      0 --:--:-- --:--:-- --:--:--  240k

✅ countries.csv
=== countries.csv flags ===
302629,"CY","Cyprus","AS","https://en.wikipedia.org/wiki/Cyprus","FLAG{e9cade1a-55a8-4af5-887d-a70ac0f3078a}"
---

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2984k  100 2984k    0     0  7744k      0 --:--:-- --:--:-- --:--:-- 7732k

✅ runways.csv
=== runways.csv flags ===
---

In [172]:
for table_name, column_name, data_type, is_nullable in desc.iter_rows():
    if data_type == 'character varying':
        
        flags = pl.read_database(f"""
          SELECT {column_name}
          FROM {table_name} 
          WHERE lower({column_name}) ILIKE '%flag%' OR lower({column_name}) ILIKE '%rkxbr3s'
        """, conn)
        if len(flags)>0:
            print(table_name, column_name)
            print(flags)

track name
shape: (1, 1)
┌───────────────────────────────────┐
│ name                              │
│ ---                               │
│ str                               │
╞═══════════════════════════════════╡
│ The Four Horsemen FLAG{e9613d97-… │
└───────────────────────────────────┘

In [176]:
full_desc = pl.read_database("""
  SELECT *
  FROM information_schema.columns 
""", conn)

In [204]:
for col in full_desc.columns:
    flags = pl.read_database(f"""
      SELECT {col}
      FROM information_schema.columns 
      WHERE lower({col}::text) ILIKE '%flag%' OR lower({col}::text) ILIKE '%rkxbr3s'
    """, conn)
    if len(flags)>0:
        print(col)
        print(flags)

'numeric'